/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MedicalHistoryRouteImport } from './routes/medical-history'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as PrescriptionsRouteImport } from './routes/prescriptions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CaseCaseIdRouteImport } from './routes/case.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalHistoryRoute = MedicalHistoryRouteImport.update({
  id: '/medical-history',
  path: '/medical-history',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsRoute = PrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseIdRoute = CaseCaseIdRouteImport.update({
  id: '/case/$caseId',
  path: '/case/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/medical-history': typeof MedicalHistoryRoute
  '/notifications': typeof NotificationsRoute
  '/patients': typeof PatientsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/settings': typeof SettingsRoute
  '/case/$caseId': typeof CaseCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/medical-history': typeof MedicalHistoryRoute
  '/notifications': typeof NotificationsRoute
  '/patients': typeof PatientsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/settings': typeof SettingsRoute
  '/case/$caseId': typeof CaseCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/medical-history': typeof MedicalHistoryRoute
  '/notifications': typeof NotificationsRoute
  '/patients': typeof PatientsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/settings': typeof SettingsRoute
  '/case/$caseId': typeof CaseCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/medical-history'
    | '/notifications'
    | '/patients'
    | '/prescriptions'
    | '/settings'
    | '/case/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/medical-history'
    | '/notifications'
    | '/patients'
    | '/prescriptions'
    | '/settings'
    | '/case/$caseId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/medical-history'
    | '/notifications'
    | '/patients'
    | '/prescriptions'
    | '/settings'
    | '/case/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MedicalHistoryRoute: typeof MedicalHistoryRoute
  NotificationsRoute: typeof NotificationsRoute
  PatientsRoute: typeof PatientsRoute
  PrescriptionsRoute: typeof PrescriptionsRoute
  SettingsRoute: typeof SettingsRoute
  CaseCaseIdRoute: typeof CaseCaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-history': {
      id: '/medical-history'
      path: '/medical-history'
      fullPath: '/medical-history'
      preLoaderRoute: typeof MedicalHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions': {
      id: '/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof PrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId': {
      id: '/case/$caseId'
      path: '/case/$caseId'
      fullPath: '/case/$caseId'
      preLoaderRoute: typeof CaseCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MedicalHistoryRoute: MedicalHistoryRoute,
  NotificationsRoute: NotificationsRoute,
  PatientsRoute: PatientsRoute,
  PrescriptionsRoute: PrescriptionsRoute,
  SettingsRoute: SettingsRoute,
  CaseCaseIdRoute: CaseCaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
